// Try catch

const numero1 = 20;
const numero3 = 40;

console.log(numero1);

// Para saber si hay un error, y seguir con el codigo a pesar del error

try {
    console.log(numero2); 
} catch (error) {
    console.log(error);
}

console.log(numero3);